export const types = {
  FETCH_TODOS: 'FETCH_TODOS',
  FETCH_TODOS_SUCCEEDED: 'FETCH_TODOS_SUCCEEDED',
  FETCH_TODOS_FAILED: 'FETCH_TODOS_FAILED',
  TODO_UPDATE: 'TODO_UPDATE',
  TODO_UPDATE_SUCCEEDED: 'TODO_UPDATE_SUCCEEDED',
  TODO_UPDATE_FAILED: 'TODO_UPDATE_FAILED',
  TODO_DELETE: 'TODO_DELETE',
  TODO_DELETE_SUCCEEDED: 'TODO_DELETE_SUCCEEDED',
  TODO_DELETE_FAILED: 'TODO_DELETE_FAILED',
  TODO_CREATE: 'TODO_CREATE',
  TODO_CREATE_SUCCEEDED: 'TODO_CREATE_SUCCEEDED',
  TODO_CREATE_FAILED: 'TODO_CREATE_FAILED',
}
